### ISSUE TITLE
Way to add comments into nex-keys.txt?

### ISSUE THREAD

**Issue by InternalLoss** [Stary2001/nex-dissector#3]
Before starting, I wanted to say thank you for this, because it's really helpful and will be extra helpful when debugging custom servers!

However, I was curious if it'd be possible to have a way to identify/comment in nex-keys.txt so that users can know what PID is which (since for example some users might have multiple consoles and wish to know which PID they'd need to share to help decrypt packets)

**Comment by mrexodia** [comment]
Just put a file next to `nex-keys.txt` with the comments 😉

**Comment by InternalLoss** [comment]
Fair ;p
I tried adding a comment but it ate the comment and turned it into a password :3
