### ISSUE TITLE
Wireshark lua error during loading

### ISSUE THREAD

**Issue by ouone** [Stary2001/nex-dissector#4]
Hi there, upon trying to install the wireshark plugin for 3DS NEX traffic, I recieve this error on startup. (Image is also attached)

`Lua: Error during loading:
...Wireshark\plugins\nex-dissector-plugin.lua:117: attempt to concatenate a nil value
stack traceback:
...Wireshark\plugins\nex-dissector-plugin.lua:117: in main chunk`

Any help in getting this working would be much appreciated :)

<img width="479" alt="wireshark-issue" src="https://user-images.githubusercontent.com/25887064/122755166-f2e7a100-d2d7-11eb-98e2-dcc71df4bdda.PNG">

**Comment by Stary2001** [comment]
This should be fixed in the latest commit! 
This was a Windows specific issue, as it uses \ in paths, but I had a function that relied on / being the path separator.

**Comment by ouone** [comment]
> This should be fixed in the latest commit!
> This was a Windows specific issue, as it uses \ in paths, but I had a function that relied on / being the path separator.

Thank you very much! All is working now :)
